rules:
 dicom_tags: 
    - tag: !!python/tuple [0x0010,0x0010]
      name: Patient's Name
    - tag: !!python/tuple [0x0010,0x0020]
      name: Patient ID
    - tag: !!python/tuple [0x0010,0x0030]
      name: Patient's Birth Date
    - tag: !!python/tuple [0x0010,0x0030]
      name: Patient's Sex
    - tag: !!python/tuple [0x0010,0x1010]
      name: Patient's Age
    - tag: !!python/tuple [0x0010,0x1020]
      name: Patient's Size
    - tag: !!python/tuple [0x0010,0x1030]
      name: Patient's Weight
    - tag: !!python/tuple [0x0010,0x1040]
      name: Patient's Address
    - tag: !!python/tuple [0x0010,0x1050]
      name: Patient's Telephone Numbers
    - tag: !!python/tuple [0x0010,0x1060]
      name: Patient's Insurance Plan
    - tag: !!python/tuple [0x0010,0x1070]
      name: Patient's Relationship Status
    - tag: !!python/tuple [0x0010,0x1000]
      name: Other Patient IDs
    - tag: !!python/tuple [0x0010,0x1001] 
      name: Other Patient Names  
    - tag: !!python/tuple [0x0010,0x1090] 
      name: Medical Record Locator
    - tag: !!python/tuple [0x0020,0x000D]
      name: Study Instance UID
    - tag: !!python/tuple [0x0020,0x0010]
      name: Study ID
    - tag: !!python/tuple [0x0008,0x0020] 
      name: Study Date
    - tag: !!python/tuple [0x0008,0x0030]
      name: Study Time
    - tag: !!python/tuple [0x0008,0x0090]
      name: Referring Physician's Name
    - tag: !!python/tuple [0x0008,0x0050]
      name: Accession Number
    - tag: !!python/tuple [0x0008,0x1030]
      name: Study Description
    - tag: !!python/tuple [0x0008,0x1048]
      name: Physician(s) of Record
    - tag: !!python/tuple [0x0008,0x1060]
      name: Name of Physician(s) Reading Study
    - tag: !!python/tuple [0x0020,0x000E]
      name: Series Instance UID
    - tag: !!python/tuple [0x0020,0x0011]
      name: Series Number
    - tag: !!python/tuple [0x0008,0x0021]
      name: Series Date
    - tag: !!python/tuple [0x0008,0x0031]
      name: Series Time
    - tag: !!python/tuple [0x0008,0x103E]
      name: Series Description
    - tag: !!python/tuple [0x0008,0x0070]
      name: Manufacturer
    - tag: !!python/tuple [0x0008,0x0080]
      name: Institution Name
    - tag: !!python/tuple [0x0008,0x1010]
      name: Station Name
    - tag: !!python/tuple [0x0008,0x1040]
      name: Institutional Department Name
    - tag: !!python/tuple [0x0008,0x1090]
      name: Manufacturer's Model Name
    - tag: !!python/tuple [0x0018,0x1000]
      name: Device Serial Number
    - tag: !!python/tuple [0x0018,0x1016]
      name: Secondary Capture Device Manufacturer
    - tag: !!python/tuple [0x0018,0x1000]
      name: Device Serial Number
    - tag: !!python/tuple [0x0018,0x1016]
      name: Secondary Capture Device Manufacturer
    - tag: !!python/tuple [0x0018,0x1018]
      name: Secondary Capture Device Manufacturer's Model Name
    - tag: !!python/tuple [0x0008,0x0018]
      name: SOP Instance UID
    - tag: !!python/tuple [0x0020,0x0052]
      name: Frame of Reference UID
    - tag: !!python/tuple [0x0020,0x0200]
      name: Synchronization Frame of Reference UID
    - tag: !!python/tuple [0x0008,0x0081]
      name: Institution Address
    - tag: !!python/tuple [0x0038,0x0010]
      name: Admission ID
    - tag: !!python/tuple [0x0038,0x0061]
      name: Discharge Diagnosis Description
    - tag: !!python/tuple [0x0038,0x0300]
      name: Current Patient Location
    - tag: !!python/tuple [0x0040,0x0001]
      name: Scheduled Station AE Title
    - tag: !!python/tuple [0x0040,0x0002]
      name: Scheduled Procedure Step Start Date
    - tag: !!python/tuple [0x0040,0x0003]
      name: Scheduled Procedure Step Start Time
    - tag: !!python/tuple [0x0040,0x0006]
      name: Scheduled Performing Physician's Name
    - tag: !!python/tuple [0x0040,0x0010]
      name: Scheduled Station Name
    - tag: !!python/tuple [0x0040,0x1001]
      name: Requested Procedure ID
    - tag: !!python/tuple [0x0040,0x1002]
      name: Reason for the Requested Procedure
    - tag: !!python/tuple [0x0040,0x2001]
      name: Reason for the Imaging Service Request
    - tag: !!python/tuple [0x0008,0x1084]
      name: Admitting Diagnoses Description
    - tag: !!python/tuple [0x0008,0x1120]
      name: Referenced Patient Sequence
    - tag: !!python/tuple [0x0010,0x21B0]
      name: Additional Patient History
    - tag: !!python/tuple [0x0038,0x0040]
      name: Discharge Diagnosis Description
    - tag: !!python/tuple [0x0040,0x0241]
      name: Performed Station AE Title
    - tag: !!python/tuple [0x0040,0x0242]
      name: Performed Station Name
    - tag: !!python/tuple [0x0040,0x0243]
      name: Performed Location
    - tag: !!python/tuple [0x0040,0x0244]
      name: Performed Procedure Step Start Date
    - tag: !!python/tuple [0x0040,0x0245]
      name: Performed Procedure Step Start Time
    - tag: !!python/tuple [0x0040,0x0253]
      name: Performed Procedure Step ID
    - tag: !!python/tuple [0x0008,0x002a]
      name: Acquisition DateTime
    - tag: !!python/tuple [0x0008,0x0022]
      name: Acquisition Date
    - tag: !!python/tuple [0x0008,0x0023]
      name: Acquisition Time
    - tag: !!python/tuple [0x0008,0x0024]
      name: Overlay Date
    - tag: !!python/tuple [0x0008,0x0025]
      name: Curve Date
    - tag: !!python/tuple [0x0008,0x0026]
      name: Overlay Time
    - tag: !!python/tuple [0x0008,0x0027]
      name: Curve Time
    - tag: !!python/tuple [0x0013,0x1013]
      name: Private tag data
    - tag: !!python/tuple [0x0008,0x0023]
      name: Content Date
    - tag: !!python/tuple [0x0008,0x0033]
      name: Content Time    
    - tag: !!python/tuple [0x0013,0x1013]
      Name: Private tag data
    - tag: !!python/tuple [0x0008,0x0023] 
      name: Additional Patient History
    - tag: !!python/tuple [0x0008,0x0094]
      name: Referring Physician's Telephone Numbers

 keywords:
    - 'Date'
    - 'Address'
    - 'Telephone Numbers'
    - 'Fax Numbers'
    - 'Address'
    - 'UID'
    - 'Time'

  # # phi_tags = [
  #           (0x0010, 0x0010),  # Patient's Name
  #           (0x0010, 0x0020),  # Patient ID
  #           (0x0010, 0x0030),  # Patient's Birth Date
  #           (0x0010, 0x0040),  # Patient's Sex
  #           (0x0010, 0x1000),  # Other Patient IDs
  #           (0x0010, 0x1001),  # Other Patient Names
  #           (0x0010, 0x1010),  # Patient's Age
  #           (0x0010, 0x1020),  # Patient's Size
  #           (0x0010, 0x1030),  # Patient's Weight
  #           (0x0010, 0x1090),  # Medical Record Locator
  #           (0x0020, 0x000D),  # Study Instance UID
  #           (0x0020, 0x0010),  # Study ID
  #           (0x0008, 0x0020),  # Study Date
  #           (0x0008, 0x0030),  # Study Time
  #           (0x0008, 0x0090),  # Referring Physician's Name
  #           (0x0008, 0x0050),  # Accession Number
  #           (0x0008, 0x1030),  # Study Description
  #           (0x0008, 0x1048),  # Physician(s) of Record
  #           (0x0008, 0x1060),  # Name of Physician(s) Reading Study
  #           (0x0020, 0x000E),  # Series Instance UID
  #           (0x0020, 0x0011),  # Series Number
  #           (0x0008, 0x0021),  # Series Date
  #           (0x0008, 0x0031),  # Series Time
  #           (0x0008, 0x103E),  # Series Description
  #           (0x0008, 0x1070),  # Operator's Name
  #           (0x0008, 0x0070),  # Manufacturer
  #           (0x0008, 0x0080),  # Institution Name
  #           (0x0008, 0x1010),  # Station Name
  #           (0x0008, 0x1040),  # Institutional Department Name
  #           (0x0008, 0x1090),  # Manufacturer's Model Name
  #           (0x0018, 0x1000),  # Device Serial Number
  #           (0x0018, 0x1016),  # Secondary Capture Device Manufacturer
  #           (0x0018, 0x1018),  # Secondary Capture Device Manufacturer's Model Name
  #           (0x0008, 0x0018),  # SOP Instance UID
  #           (0x0020, 0x0052),  # Frame of Reference UID
  #           (0x0020, 0x0200),  # Synchronization Frame of Reference UID
  #           (0x0008, 0x0081),  # Institution Address
  #           (0x0038, 0x0010),  # Admission ID
  #           (0x0038, 0x0061),  # Discharge Diagnosis Description
  #           (0x0038, 0x0300),  # Current Patient Location
  #           (0x0040, 0x0001),  # Scheduled Station AE Title
  #           (0x0040, 0x0002),  # Scheduled Procedure Step Start Date
  #           (0x0040, 0x0003),  # Scheduled Procedure Step Start Time
  #           (0x0040, 0x0006),  # Scheduled Performing Physician's Name
  #           (0x0040, 0x0010),  # Scheduled Station Name
  #           (0x0040, 0x1001),  # Requested Procedure ID
  #           (0x0040, 0x1002),  # Reason for the Requested Procedure
  #           (0x0040, 0x2001),  # Reason for the Imaging Service Request
  #           (0x0008, 0x1084),  # Admitting Diagnoses Description
  #           (0x0008, 0x1120),  # Referenced Patient Sequence
  #           (0x0010, 0x21B0),  # Additional Patient History
  #           (0x0038, 0x0040),  # Discharge Diagnosis Description
  #           (0x0040, 0x0241),  # Performed Station AE Title
  #           (0x0040, 0x0242),  # Performed Station Name
  #           (0x0040, 0x0243),  # Performed Location
  #           (0x0040, 0x0244),  # Performed Procedure Step Start Date
  #           (0x0040, 0x0245),  # Performed Procedure Step Start Time
  #           (0x0040, 0x0253),  # Performed Procedure Step ID
  #           (0x0008, 0x002a),  # Acquisition DateTime
  #           (0x0008, 0x0022),  # Acquisition Date
  #           (0x0008, 0x0023),  # Content Date
  #           (0x0008, 0x0033),  # Content Time 
  #           (0x0008, 0x0024),  # Overlay Date
  #           (0x0008, 0x0025),  # Curve Date 
  #           (0x0008, 0x0026),  # Overlay Time
  #           (0x0008, 0x0027),  # Curve Time
  #           (0x0008, 0x0028),  # Acquisition Time
  #           (0x0008, 0x0029),  # Acquisition Duration
  #           (0x0008, 0x002b),  # Acquisition Number
  #           (0x0008, 0x0016),  # SOP Class UID
  #           (0x0088, 0x0140),  # Storage Media File-set UID
  #           (0x0008, 0x0094),  # Referring Physician's Telephone Numbers
  #           (0x0013, 0x1013),  # Name: Private tag data
  #       ]